export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const MOVE_PRODUCT = 'MOVE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_WAREHOUSES_FROM_PRODUCTS = 'DELETE_WAREHOUSES_FROM_PRODUCTS'